# for preprocessing
ELECTRON_PT_LOWER_BOUND = 20.0 
MUON_PT_LOWER_BOUND = 20.0

ELECTRON_R_LOWER_BOUND = 0.4
MUON_R_LOWER_BOUND = 0.4
MATCHED_GEN_R_LOWER_BOUND = 0.4

FATJET_PT_LOWER_BOUND = 200.0
FATJET_ETA_BOUNDS = 2.0

FATJET_DELTA_ETA_BOUND = 0.1 
FATJET_DELTA_PHI_BOUND = 0.1 
FATJET_DELTA_PT_BOUND = 1

# for histogram binning
ETA_MIN = -0.8 
ETA_MAX = 0.8 
PHI_MIN = -0.8 
PHI_MAX = 0.8 
INCR = 0.05 
