# configs/config.yaml

# Paths
data:
  raw_data_dir: data/raw/
  processed_data_dir: data/processed/
  train_file: datatype1small.pkl
  test_file: datatype2small.pkl

# Model Hyperparameters
model:
  num_features: 5
  smallest_dim: 16
  num_reduced_edges: 16
  batch_size: 64

# Training Settings
training:
  initial_lr: 0.000005
  epochs: 10
  device: cuda  # Options: 'cuda' or 'cpu'

# Other
misc:
  k_nearest_neighbors: 16
  node_feature_names: ['pt', 'eta', 'phi', 'd0/d0Err', 'dz/dzErr']