# configs/config.yaml

# Debugging
dbg:
  measure_perf: true
  # 10: DEBUG; 20: INFO; 30: WARNING; 40: ERROR
  logging_level: 20
  only_one_progress_bar: false
  show_plots: false

# Paths
data:
  # jet_type
  background: qcd
  signal: wjet
  
  #raw_qcd: /isilon/export/home/mstamenk/jet-anomaly-summer25/downloads/jekrupa/v2_2/2017/QCD/QCD_Pt_1000to1400_TuneCP5_13TeV_pythia8/QCD_Pt_1000to1400/211109_133059/0000/
  #raw_wjet: /isilon/export/home/mstamenk/jet-anomaly-summer25/downloads/jekrupa/v2_2/2017/WJetsToQQ/WJetsToQQ_HT-400to600_TuneCP5_13TeV-madgraphMLM-pythia8/WJetsToQQ_HT-400to600/211108_171900/0000/
  # local/symlinked data
  raw_qcd: data/raw/qcd/
  raw_wjet: data/raw/wjet/
  # after preprocessing, move the raw data file into a subfolder?
  move_to_used: true
  
  preprocessed_qcd: data/preprocessed/qcd/qcd_with_metadata2
  preprocessed_wjet: data/preprocessed/wjet
  processed_data_dir: data/processed/scaledby_QCD_PT-80to470/scaledby_QCD/

  background_file: QCD_scaled.pkl
  signal_file: WJet_scaled.pkl

  bins: 50

# Model Hyperparameters
model:
  num_features: 5
  smallest_dim: 4
  num_reduced_edges: 16
  batch_size: 64

# Training Settings
training:
  initial_lr: 0.00005
  epochs: 50
  device: cpu  # Options: 'cuda' or 'cpu'
  alpha: 0.3

# Other
misc:
  k_nearest_neighbors: 32
  node_feature_names: ['pt', 'eta', 'phi', 'd0/d0Err', 'dz/dzErr']
